version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
      - db
  ai:
    build: ./ai
    ports:
      - "5001:5001"
volumes:
  pgdata: