spring:
  datasource:
    url: jdbc:postgresql://db:5432/smarthome
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8080
mqtt:
  broker: tcp://mosquitto:1883